# Generated by Django 4.2.2 on 2023-06-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='career_advice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
