# Generated by Django 4.2.2 on 2023-06-25 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='respondent',
        ),
        migrations.AddField(
            model_name='question',
            name='respondent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='asker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asked_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
