# Generated by Django 4.2.2 on 2023-08-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_message_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailthread',
            name='has_unread',
        ),
    ]
