# Generated by Django 4.2.2 on 2023-08-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_remove_mailthread_has_unread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
