# Generated by Django 4.2.2 on 2023-07-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-likes', '-updated', '-created']},
        ),
    ]
